server:
  port: 8009
  servlet:
    context-path: /screw
spring:
  datasource:
    url: jdbc:mysql://192.168.3.43:3306/aaa?characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 20
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池名称
      pool-name: MyHikariCP
      ## 控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 180000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      ## 数据库连接保持连接心跳
      connection-test-query: select 1